pipeline:
  release:
    image: registry.usw.co/uswitch/clojure
    secrets: [ CLOJARS_USERNAME, CLOJARS_PASSWORD ]
    when:
      branch: master
      event: push
    commands:
      - lein deps
      - lein codox
      - lein jar
      - lein deploy clojars

  build-gh-pages:
    image: registry.usw.co/uswitch/clojure
    when:
      branch: master
      event: push
    commands:
      - lein codox
      - mkdir .docs && mv target/doc/* .docs/
      - rm -r * && rm .gitignore && rm .drone.yml
      - mv .docs/* . && rmdir .docs

  push-gh-pages:
    image: registry.usw.co/drone/deployment
    when:
      branch: master
      event: push
    commands:
      - git config user.name dodgydrone
      - git config user.email drone@drone.drone
      - git checkout --orphan gh-pages
      - git add .
      - git commit -m "dox"
      - git push -f origin gh-pages
