pipeline:
  release:
    image: registry.usw.co/uswitch/clojure
    secrets: [ CLOJARS_USERNAME, CLOJARS_PASSWORD ]
    when:
      branch: master
      event: push
    commands:
      - lein deps
      - lein jar
      - lein deploy clojars
